In [1]:
import pandas as pd

rows = [
    ['d', 'a', 'd', 'c', 'c', 'b', 'e', 'b', 'c', 'c'],
    ['e', 'a', 'b', 'c', 'd', 'd', 'c', 'b', 'a', 'c'],
    ['a', 'a', 'b', 'c', 'a', 'd', 'c', 'b', 'd', 'e'],
    ['a', 'c', 'd', 'b', 'b', 'a', 'a', 'b', 'd', 'e'],
    ['a', 'c', 'b', 'a', 'a', 'a', 'e', 'b', 'd', 'd'],
    ['e', 'a', 'e', 'c', 'c', 'a', 'c', 'd', 'b', 'a'],
    ['a', 'e', 'b', 'a', 'c', 'a', 'd', 'a', 'b', 'd'],
    ['a', 'a', 'b', 'd', 'b', 'a', 'e', 'b', 'd', 'c'],
    ['b', 'a', 'a', 'a', 'b', 'a', 'd', 'd', 'b', 'd'],
    ['a', 'e', 'e', 'a', 'b', 'a', 'c', 'c', 'a', 'e'],
    ['a', 'e', 'b', 'a', 'd', 'a', 'e', 'c', 'b', 'c'],
    ['a', 'a', 'b', 'c', 'd', 'a', 'e', 'd', 'd', 'd'],
    ['a', 'e', 'b', 'd', 'b', 'a', 'c', 'e', 'c', 'e'],
    ['e', 'e', 'b', 'b', 'a', 'a', 'c', 'b', 'c', 'e'],
    ['c', 'a', 'e', 'c', 'd', 'd', 'c', 'b', 'a', 'c'],
    ['a', 'c', 'b', 'a', 'e', 'a', 'e', 'c', 'b', 'b'],
    ['c', 'e', 'a', 'a', 'a', 'a', 'c', 'b', 'a', 'c'],
    ['a', 'e', 'e', 'a', 'a', 'a', 'd', 'b', 'e', 'd'],
    ['b', 'e', 'b', 'a', 'a', 'a', 'c', 'b', 'd', 'e'],
    ['a', 'd', 'c', 'e', 'c', 'a', 'd', 'b', 'c', 'e'],
    ['a', 'c', 'b', 'a', 'a', 'a', 'c', 'b', 'd', 'c'],
    ['a', 'e', 'b', 'a', 'c', 'a', 'e', 'b', 'd', 'c'],
    ['a', 'a', 'b', 'c', 'd', 'a', 'e', 'b', 'b', 'a'],
    ['c', 'a', 'a', 'b', 'd', 'a', 'e', 'c', 'd', 'd'],
    ['d', 'a', 'b', 'a', 'b', 'd', 'd', 'c', 'c', 'e'],
    ['e', 'c', 'a', 'b', 'b', 'a', 'e', 'b', 'd', 'b'],
    ['a', 'e', 'a', 'a', 'b', 'a', 'd', 'e', 'b', 'e'],
    ['a', 'e', 'b', 'a', 'c', 'a', 'c', 'b', 'd', 'c'],
    ['a', 'a', 'b', 'c', 'c', 'a', 'e', 'd', 'd', 'c'],
    ['a', 'c', 'b', 'a', 'a', 'a', 'e', 'b', 'b', 'c'],
    ['a', 'a', 'd', 'c', '-', 'a', 'e', 'b', 'd', 'c'],
    ['a', 'a', 'c', 'a', 'b', 'e', 'e', 'b', 'e', 'b'],
    ['a', 'b', 'b', 'c', 'a', 'a', 'c', 'c', 'd', 'c'],
    ['c', 'a', 'a', 'b', 'b', 'a', 'e', 'e', 'd', 'c'],
    ['a', 'b', 'b', 'a', 'd', 'e', 'e', 'c', 'b', 'a'],
    ['e', 'a', 'b', 'c', 'b', 'a', 'e', 'd', 'd', 'd'],
    ['a', 'c', 'a', 'c', 'c', 'a', 'a', 'b', 'd', 'c'],
    ['b', 'c', 'b', 'a', 'a', 'a', 'e', 'b', 'b', 'c'],
    ['e', 'a', 'b', 'c', 'b', 'a', 'b', 'd', 'd', 'd']
]
df = pd.DataFrame(rows, columns=['q1', 'q2', 'q3', 'q4', 'q5', 'q6', 'q7', 'q8', 'q9', 'q10'])

gabarito = ['a', 'e', 'b', 'a', 'c', 'a', 'e', 'b', 'd', 'c']

In [2]:
def calcular_notas(linha):
    return sum(i for i, resposta in enumerate(linha) if resposta == gabarito[i])

In [3]:
sum(1 for i, resposta in enumerate(gabarito) if resposta == gabarito[i])

10

In [4]:
df.apply(calcular_notas, axis=1)

0     26
1     18
2     17
3     20
4     31
5      9
6     15
7     37
8      8
9      9
10    26
11    21
12     8
13    15
14    16
15    16
16    25
17    16
18    26
19    16
20    34
21    45
22    20
23    19
24     5
25    26
26     9
27    39
28    34
29    32
30    35
31    16
32    24
33    28
34    11
35    21
36    33
37    32
38    15
dtype: int64

descobrindo quem acertou a questão 5

In [5]:
df['Nota'] = df.apply(calcular_notas, axis = 1)
df

   q1 q2 q3 q4 q5 q6 q7 q8 q9 q10  Nota
0   d  a  d  c  c  b  e  b  c   c    26
1   e  a  b  c  d  d  c  b  a   c    18
2   a  a  b  c  a  d  c  b  d   e    17
3   a  c  d  b  b  a  a  b  d   e    20
4   a  c  b  a  a  a  e  b  d   d    31
5   e  a  e  c  c  a  c  d  b   a     9
6   a  e  b  a  c  a  d  a  b   d    15
7   a  a  b  d  b  a  e  b  d   c    37
8   b  a  a  a  b  a  d  d  b   d     8
9   a  e  e  a  b  a  c  c  a   e     9
10  a  e  b  a  d  a  e  c  b   c    26
11  a  a  b  c  d  a  e  d  d   d    21
12  a  e  b  d  b  a  c  e  c   e     8
13  e  e  b  b  a  a  c  b  c   e    15
14  c  a  e  c  d  d  c  b  a   c    16
15  a  c  b  a  e  a  e  c  b   b    16
16  c  e  a  a  a  a  c  b  a   c    25
17  a  e  e  a  a  a  d  b  e   d    16
18  b  e  b  a  a  a  c  b  d   e    26
19  a  d  c  e  c  a  d  b  c   e    16
20  a  c  b  a  a  a  c  b  d   c    34
21  a  e  b  a  c  a  e  b  d   c    45
22  a  a  b  c  d  a  e  b  b   a    20
23  c  a  a  b  d  a  e  c  d   d    19
24  d  a  b  a  b  d  d  c  c   e     5
25  e  c  a  b  b  a  e  b  d   b    26
26  a  e  a  a  b  a  d  e  b   e     9
27  a  e  b  a  c  a  c  b  d   c    39
28  a  a  b  c  c  a  e  d  d   c    34
29  a  c  b  a  a  a  e  b  b   c    32
30  a  a  d  c  -  a  e  b  d   c    35
31  a  a  c  a  b  e  e  b  e   b    16
32  a  b  b  c  a  a  c  c  d   c    24
33  c  a  a  b  b  a  e  e  d   c    28
34  a  b  b  a  d  e  e  c  b   a    11
35  e  a  b  c  b  a  e  d  d   d    21
36  a  c  a  c  c  a  a  b  d   c    33
37  b  c  b  a  a  a  e  b  b   c    32
38  e  a  b  c  b  a  b  d  d   d    15

In [6]:
df['q5'].apply(lambda x : 'Sim' if x == 'c' else 'Não')

0     Sim
1     Não
2     Não
3     Não
4     Não
5     Sim
6     Sim
7     Não
8     Não
9     Não
10    Não
11    Não
12    Não
13    Não
14    Não
15    Não
16    Não
17    Não
18    Não
19    Sim
20    Não
21    Sim
22    Não
23    Não
24    Não
25    Não
26    Não
27    Sim
28    Sim
29    Não
30    Não
31    Não
32    Não
33    Não
34    Não
35    Não
36    Sim
37    Não
38    Não
Name: q5, dtype: str

In [7]:
df['q5']

0     c
1     d
2     a
3     b
4     a
5     c
6     c
7     b
8     b
9     b
10    d
11    d
12    b
13    a
14    d
15    e
16    a
17    a
18    a
19    c
20    a
21    c
22    d
23    d
24    b
25    b
26    b
27    c
28    c
29    a
30    -
31    b
32    a
33    b
34    d
35    b
36    c
37    a
38    b
Name: q5, dtype: str

In [8]:
def test(x):
    if x == 'c':
        return 'Sim'
    else:
        return 'Não'

In [9]:
df['Nota_maior_5'] = df['Nota'].apply(lambda x : 'Nota >= 5' if x >= 5 else 'Nota<5')

In [10]:
df

   q1 q2 q3 q4 q5 q6 q7 q8 q9 q10  Nota Nota_maior_5
0   d  a  d  c  c  b  e  b  c   c    26    Nota >= 5
1   e  a  b  c  d  d  c  b  a   c    18    Nota >= 5
2   a  a  b  c  a  d  c  b  d   e    17    Nota >= 5
3   a  c  d  b  b  a  a  b  d   e    20    Nota >= 5
4   a  c  b  a  a  a  e  b  d   d    31    Nota >= 5
5   e  a  e  c  c  a  c  d  b   a     9    Nota >= 5
6   a  e  b  a  c  a  d  a  b   d    15    Nota >= 5
7   a  a  b  d  b  a  e  b  d   c    37    Nota >= 5
8   b  a  a  a  b  a  d  d  b   d     8    Nota >= 5
9   a  e  e  a  b  a  c  c  a   e     9    Nota >= 5
10  a  e  b  a  d  a  e  c  b   c    26    Nota >= 5
11  a  a  b  c  d  a  e  d  d   d    21    Nota >= 5
12  a  e  b  d  b  a  c  e  c   e     8    Nota >= 5
13  e  e  b  b  a  a  c  b  c   e    15    Nota >= 5
14  c  a  e  c  d  d  c  b  a   c    16    Nota >= 5
15  a  c  b  a  e  a  e  c  b   b    16    Nota >= 5
16  c  e  a  a  a  a  c  b  a   c    25    Nota >= 5
17  a  e  e  a  a  a  d  b  e   d    16    Nota >= 5
18  b  e  b  a  a  a  c  b  d   e    26    Nota >= 5
19  a  d  c  e  c  a  d  b  c   e    16    Nota >= 5
20  a  c  b  a  a  a  c  b  d   c    34    Nota >= 5
21  a  e  b  a  c  a  e  b  d   c    45    Nota >= 5
22  a  a  b  c  d  a  e  b  b   a    20    Nota >= 5
23  c  a  a  b  d  a  e  c  d   d    19    Nota >= 5
24  d  a  b  a  b  d  d  c  c   e     5    Nota >= 5
25  e  c  a  b  b  a  e  b  d   b    26    Nota >= 5
26  a  e  a  a  b  a  d  e  b   e     9    Nota >= 5
27  a  e  b  a  c  a  c  b  d   c    39    Nota >= 5
28  a  a  b  c  c  a  e  d  d   c    34    Nota >= 5
29  a  c  b  a  a  a  e  b  b   c    32    Nota >= 5
30  a  a  d  c  -  a  e  b  d   c    35    Nota >= 5
31  a  a  c  a  b  e  e  b  e   b    16    Nota >= 5
32  a  b  b  c  a  a  c  c  d   c    24    Nota >= 5
33  c  a  a  b  b  a  e  e  d   c    28    Nota >= 5
34  a  b  b  a  d  e  e  c  b   a    11    Nota >= 5
35  e  a  b  c  b  a  e  d  d   d    21    Nota >= 5
36  a  c  a  c  c  a  a  b  d   c    33    Nota >= 5
37  b  c  b  a  a  a  e  b  b   c    32    Nota >= 5
38  e  a  b  c  b  a  b  d  d   d    15    Nota >= 5

In [11]:
tabela_contingencia = pd.crosstab(df['Acertouq5'], df['Nota_maior_5'], margin=True, margins_name="Total")

tabela_contingencia

KeyError: 'Acertouq5'

# DAQUI PRA BAIXO É DE 24-03-2026

In [13]:
notas = df['Nota'].tolist()

In [15]:
import numpy as np

In [16]:
bins = [0, 2, 4, 6, 8, 10]

counts, limitebin = np.histogram(notas)
print(counts, limitebin)

[3 4 8 5 3 6 3 4 2 1] [ 5.  9. 13. 17. 21. 25. 29. 33. 37. 41. 45.]

In [19]:
cdf = pd.DataFrame(counts)
cdf['freq_rel'] = cdf[0]/np.sum(counts)
cdf

   0  freq_rel
0  3  0.076923
1  4  0.102564
2  8  0.205128
3  5  0.128205
4  3  0.076923
5  6  0.153846
6  3  0.076923
7  4  0.102564
8  2  0.051282
9  1  0.025641

In [26]:
bin_labels = [f"[{int(limitebin[i])} - {int(limitebin[i+1])}]" for i in range(len(limitebin)-1)]
bin_labels[4] = '[8-10]'

cdf = pd.DataFrame({'Faixa': bin_labels, 'Freq_abs': counts})
cdf['Freq_rel'] = cdf['Freq_abs']/np.sum(counts)

cdf['Freq_acumulada']=cdf['Freq_abs'].cumsum()

cdf

       Faixa  Freq_abs  Freq_rel  Freq_acumulada
0    [5 - 9]         3  0.076923               3
1   [9 - 13]         4  0.102564               7
2  [13 - 17]         8  0.205128              15
3  [17 - 21]         5  0.128205              20
4     [8-10]         3  0.076923              23
5  [25 - 29]         6  0.153846              29
6  [29 - 33]         3  0.076923              32
7  [33 - 37]         4  0.102564              36
8  [37 - 41]         2  0.051282              38
9  [41 - 45]         1  0.025641              39

derivada é a diferença de um ponto (elemento) ao outro

In [27]:
np.mean(notas)

np.float64(21.871794871794872)

In [28]:
pontos_medio = [1, 3, 5, 7, 9]

media_hist = sum(c*p for c,p in zip(counts, pontos_medio))/39
media_hist

np.float64(3.0)

In [ ]:
f_md = fr[4]